version: '2'
services:
  mariadb:
    image: 'bitnami/mariadb:10.3'
    environment:
      - MARIADB_USER=bn_wordpress
      - MARIADB_DATABASE=bitnami_wordpress
      - ALLOW_EMPTY_PASSWORD=yes
  wordpress:
    build: 'docker/'
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - mariadb
    environment:
      - REPOSITORY=${REPOSITORY}
      - BRANCH=${BRANCH}
      - URL=${URL}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
