name: Build Staging Docker Image
on: [push]

jobs:
  build:
    name: Webhook
    runs-on: ubuntu-latest
    steps:
      - name: Webhook
        uses: zzzze/webhook-trigger@master
        with:
          webhook_url: ${{ secrets.WEBHOOK_URL }}
          data: "{'ref': 'master', 'token':'${{ secrets.TOKEN }}', 'variables[BUILD_TARGET]':'wordpress-stag', 'variables[BUILD_TARGET_BRANCH]':'${{ github.ref }}'}"