name: Build Staging Docker Image
on: [push]

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST --form "ref=master" --form "token=${{ secrets.TOKEN }}" --form "variables[BUILD_TARGET]=wordpress-stag" --form "variables[BUILD_TARGET_BRANCH]="${GITHUB_REF##*/}" "${{ secrets.WEBHOOK_URL }}"