name: Build Docker Image
on: [release]

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@v1
      with:
        args: -X POST --form "ref=master" --form "token=${{ secrets.TOKEN }}" --form "variables[BUILD_TARGET]=wordpress" --form "variables[BUILD_TARGET_BRANCH]=${GITHUB_REF##*/}" "${{ secrets.WEBHOOK_URL }}"